nohup: ignoring input
2020-04-20 01:16:45.722428: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-04-20 01:16:45.722744: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-04-20 01:16:45.723895: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/g348286/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
2020-04-20 01:16:48,050:: INFO - Setup completed
2020-04-20 01:16:48,528:: INFO - Bug reports file read.
2020-04-20 01:16:48,528:: INFO - Reports - Total: 10000 Positive: 766 (7.66% of total)
2020-04-20 01:16:50,854:: INFO - Bug reports long_description cleaned.
2020-04-20 01:16:52,004:: INFO - Data tokenized
2020-04-20 01:16:52,004:: INFO - Found 71081 unique tokens, using 100 terms.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./prediction_using_lstm.py", line 193, in <module>
    logging.info('Shape of data tensor:', X.shape)
Message: 'Shape of data tensor:'
Arguments: ((10000, 100),)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./prediction_using_lstm.py", line 196, in <module>
    logging.info('Shape of label tensor:', Y.shape)
Message: 'Shape of label tensor:'
Arguments: ((10000, 2),)
2020-04-20 01:16:52,015:: INFO - Data pre-processed
2020-04-20 01:16:52,017:: INFO - Spliting data started
2020-04-20 01:16:52,029:: INFO - Training shape    : (6400, 100) (6400, 2)
2020-04-20 01:16:52,029:: INFO - Validation shape  : (1600, 100) (1600, 2)
2020-04-20 01:16:52,029:: INFO - Test shape        : (2000, 100) (2000, 2)
2020-04-20 01:16:52,029:: INFO - Spliting data concluded
2020-04-20 01:22:48,867:: INFO - Data tokenized
2020-04-20 01:22:48,923:: INFO - Found 71081 unique tokens, using 150 terms.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./prediction_using_lstm.py", line 193, in <module>
    logging.info('Shape of data tensor:', X.shape)
Message: 'Shape of data tensor:'
Arguments: ((10000, 150),)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "./prediction_using_lstm.py", line 196, in <module>
    logging.info('Shape of label tensor:', Y.shape)
Message: 'Shape of label tensor:'
Arguments: ((10000, 2),)
2020-04-20 01:22:48,950:: INFO - Data pre-processed
2020-04-20 01:22:48,950:: INFO - Spliting data started
2020-04-20 01:22:48,969:: INFO - Training shape    : (6400, 150) (6400, 2)
2020-04-20 01:22:48,969:: INFO - Validation shape  : (1600, 150) (1600, 2)
2020-04-20 01:22:48,970:: INFO - Test shape        : (2000, 150) (2000, 2)
2020-04-20 01:22:48,970:: INFO - Spliting data concluded
